name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - ../labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: ../labels.yml
          repository: |
            PLAIF-dev/picus_m
            PLAIF-dev/.github
            PLAIF-dev/core_template
          token: ${{ secrets.GITHUB_TOKEN }}
