name: Sync labels
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          repository: |
            PLAIF-dev/picus_m
            Gosrock/Ticket-Backend-22th
            Gosrock/Ticket-Deploy-22th
            Gosrock/Ticket-Admin-22th
            Gosrock/.github
          token: ${{ secrets.GITHUB_TOKEN }}
